<?php

class InsertDefaultExercises extends Migration
{
    public function up()
    {
        DB::table('exercises')->insert([
            ['name' => 'Barbell Bench Press'],
            ['name' => 'Dumbbell Bench Press'],
            ['name' => 'Incline Barbell Bench Press'],
            ['name' => 'Incline Dumbbell Bench Press'],
            ['name' => 'Decline Barbell Bench Press'],
            ['name' => 'Decline Dumbbell Bench Press'],
            ['name' => 'Chest Press Machine'],
            ['name' => 'Incline Chest Press Machine'],
            ['name' => 'Decline Chest Press Machine'],
            ['name' => 'Dip'],
            ['name' => 'Push-Up'],
            ['name' => 'Dumbbell Fly'],
            ['name' => 'Incline Dumbbell Fly'],
            ['name' => 'Decline Dumbbell Fly'],
            ['name' => 'Pec Deck Machine'],
            ['name' => 'Cable Crossovers'],
            ['name' => 'Cable Fly'],
            ['name' => 'Pull-Up'],
            ['name' => 'Chin-Up'],
            ['name' => 'Lat Pull-Down'],
            ['name' => 'Bent Over Barbell Row'],
            ['name' => 'Dumbbell Row'],
            ['name' => 'T-Bar Row'],
            ['name' => 'Seated Cable Row'],
            ['name' => 'Pendlay Row'],
            ['name' => 'Chest Supported Barbell Row'],
            ['name' => 'Chest supported Dumbbell Row'],
            ['name' => 'Chest Supported Machine Row'],
            ['name' => 'Inverted Row'],
            ['name' => 'Barbell Shrug'],
            ['name' => 'Dumbbell Shrug'],
            ['name' => 'Machine Shrug'],
            ['name' => 'Seated Overhead Barbell Press'],
            ['name' => 'Seated Overhead Dumbbell Press'],
            ['name' => 'Standing Overhead Barbell Press'],
            ['name' => 'Standing Overhead Dumbbell Press'],
            ['name' => 'Overhead Machine Press'],
            ['name' => 'Arnold Press'],
            ['name' => 'Barbell Upright Row'],
            ['name' => 'Dumbbell Upright Row'],
            ['name' => 'Machine Upright Row'],
            ['name' => 'Dumbbell Lateral Raise'],
            ['name' => 'Cable Lateral Raise'],
            ['name' => 'Machine Lateral Raise'],
            ['name' => 'Dumbbell Front Raise'],
            ['name' => 'Cable Front Raise'],
            ['name' => 'Machine Front Raise'],
            ['name' => 'Barbell Rear Delt Row'],
            ['name' => 'Dumbbell Rear Delt Row'],
            ['name' => 'Machine Rear Delt Row'],
            ['name' => 'Dumbbell Rear Delt Raises'],
            ['name' => 'Barbell Squat'],
            ['name' => 'Dumbbell Squat'],
            ['name' => 'Barbell Front Squat'],
            ['name' => 'Dumbbell Front Squat'],
            ['name' => 'Barbell Split Squat'],
            ['name' => 'Dumbbell Split Squat'],
            ['name' => 'Barbell Lunge'],
            ['name' => 'Dumbbell Lunge'],
            ['name' => 'Barbell Step-Up'],
            ['name' => 'Dumbbell Step-Up'],
            ['name' => 'Leg Press'],
            ['name' => 'Machine Squat'],
            ['name' => 'Hack Squat'],
            ['name' => 'Leg Extension'],
            ['name' => 'Barbell Romanian Deadlift'],
            ['name' => 'Dumbbell Romanian Deadlift'],
            ['name' => 'Barbell Straight Leg Deaflift'],
            ['name' => 'Dumbbell Straight Leg Deadlift'],
            ['name' => 'Barbell Sumo Deaflit'],
            ['name' => 'Dumbbell Sumo Deadlift'],
            ['name' => 'Glute-Ham Raise'],
            ['name' => 'Hyperextension'],
            ['name' => 'Cable Pull-Through'],
            ['name' => 'Good-Mornings'],
            ['name' => 'Leg Curl'],
            ['name' => 'Standing Barbell Curl'],
            ['name' => 'Dumbbell Curl'],
            ['name' => 'Barbell Preacher Curl'],
            ['name' => 'Dumbbell Preacher Curl'],
            ['name' => 'Seated Dumbbell Curl'],
            ['name' => 'Incline Dumbbell Curl'],
            ['name' => 'Hammer Curl'],
            ['name' => 'Concentration Curl'],
            ['name' => 'Cable Curl'],
            ['name' => 'Biceps Curl Machine'],
            ['name' => 'Close Grip Bench Press'],
            ['name' => 'Decline Close Grip Bench Press'],
            ['name' => 'Close Grip Push-Up'],
            ['name' => 'Laying Barbell Extension'],
            ['name' => 'Dumbbell Triceps Extension'],
            ['name' => 'Skull Crusher'],
            ['name' => 'Overhead Barbell Triceps Extension'],
            ['name' => 'Overhead Dumbbell Triceps Extension'],
            ['name' => 'Cable Press-Down'],
            ['name' => 'Bench Dip'],
            ['name' => 'Standing Calf Raise'],
            ['name' => 'Seated Calf Raise']
        ]);
    }

    public function down()
    {
        DB::table('exercises')->whereNull('user_id')->delete();
    }
}
